### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'benchmark_nerf_synthetic_ours_stmt/mic/cfg_args'

### ISSUE THREAD

**Issue by gongyan1** [autonomousvision/mip-splatting#35]
Looking for config file in benchmark_nerf_synthetic_ours_stmt/mic/cfg_args
Traceback (most recent call last):
  File "render.py", line 60, in <module>
    args = get_combined_args(parser)
  File "/home/jovyan/cfs/personal_data/gongyan/It/mip-splatting-main/arguments/__init__.py", line 105, in get_combined_args
    with open(cfgfilepath) as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'benchmark_nerf_synthetic_ours_stmt/mic/cfg_args'

**Comment by niujinshuchong** [comment]
Hi, maybe you need to train the model first before the evaluation.
