### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'kernel_size'

### ISSUE THREAD

**Issue by Interstellar6** [autonomousvision/mip-splatting#53]
I try to run `python scripts/run_mipnerf360.py` but this error occured.

How can I handle it ?

```
(gaussian_splatting) z@iipl:~/mip-splatting$ python scripts/run_mipnerf360.py
Starting job on GPU 0 with scene flowers

OMP_NUM_THREADS=4 CUDA_VISIBLE_DEVICES=0 python train.py -s 360_v2/flowers -m benchmark_360v2_ours/flowers --eval -r 4 --port 6009 --kernel_size 0.1
Optimizing benchmark_360v2_ours/flowers
Output folder: benchmark_360v2_ours/flowers [19/10 15:16:26]
Tensorboard not available: not logging progress [19/10 15:16:26]
Reading camera 173/173 [19/10 15:17:14]
Loading Training Cameras [19/10 15:17:14]
Loading Test Cameras [19/10 15:18:25]
Number of points at initialisation :  38347 [19/10 15:18:33]
Computing 3D filter [19/10 15:18:33]
Training progress:   0%|                                                 | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 268, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 125, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background, kernel_size=dataset.kernel_size, subpixel_offset=subpixel_offset)
  File "/data0/z/mip-splatting/gaussian_renderer/__init__.py", line 53, in render
    debug=pipe.debug
TypeError: __new__() got an unexpected keyword argument 'kernel_size'
Training progress:   0%|                                                 | 0/30000 [00:00<?, ?it/s]
```

**Comment by PWZ-droid** [comment]
I meet the similar problem. Have you fixed it up?

**Comment by PWZ-droid** [comment]
Hi, I figured out the problem. I reinstalled diff-gaussian-rasterization, and that solved the issue.

**Comment by Interstellar6** [comment]
> Hi, I figured out the problem. I reinstalled diff-gaussian-rasterization, and that solved the issue.

Thanks a lot, I also solve the problem. The comment will be closed.
